name: data-ingestion test & deploy
on:
    - push

jobs:
    standard_tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: init
              working-directory: ./data_ingestion
              run: make init
            - name: standard-check
              run: make standard-checks
              working-directory: ./data_ingestion