name: data-ingestion test & deploy
on:
    - push

jobs:
    standard_tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: init
              run: make init
            - name: standard-check
              run: make standards

    unit_tests:
        runs-on: ubuntu-latest
        needs: standard_tests
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: init
              run: make init
            - name: unit-tests
              run: make unit-tests
            - name: Coveralls
              uses: coverallsapp/github-action@v2
    deploy:
      runs-on: ubuntu-latest
      needs: unit_tests
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Configure AWS CLI
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2

        - name: Setup terraform
          uses: hashicorp/setup-terraform@v2
  
        - name: Terraform init
          run: >
            terraform -chdir=./terraform init
  
        - name: Terraform plan
          run: >
            terraform -chdir=./terraform plan
            -var="db_credentials_olap=${{secrets.DB_CREDENTIALS_OLAP}}"
            -var="db_credentials_oltp=${{secrets.DB_CREDENTIALS_OLTP}}"
            -var="sns_emails=${{secrets.SNS_EMAILS}}"
  
        - name: Terraform apply
          run: >
            terraform -chdir=./terraform apply
            -auto-approve
            -var="db_credentials_olap=${{secrets.DB_CREDENTIALS_OLAP}}"
            -var="db_credentials_oltp=${{secrets.DB_CREDENTIALS_OLTP}}"
            -var="sns_emails=${{secrets.SNS_EMAILS}}"